# Generated by Django 4.2.5 on 2023-09-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(default='images/1.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='drink',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='thumbnail',
            field=models.ImageField(blank=True, default='thumbnails/1.jpg', null=True, upload_to='thumbnails/'),
        ),
    ]
