# Generated by Django 4.2.5 on 2023-09-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(default='static/images/1.jpg', upload_to='static/images/'),
        ),
    ]
