# Generated by Django 4.2.5 on 2023-09-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_ingredient_ingredient_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='drinkName',
            new_name='drink_name',
        ),
    ]
