# Generated by Django 4.2.5 on 2023-09-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_drinkname_drink_drink_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='createDate',
            new_name='creation_date',
        ),
    ]
