# Generated by Django 4.2.5 on 2023-09-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_ingredient_ingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_amount',
            field=models.PositiveIntegerField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('15', 15), ('20', 20), ('25', 25), ('30', 30), ('35', 35), ('40', 40), ('45', 45), ('50', 50), ('60', 60), ('70', 70), ('80', 80), ('90', 90), ('100', 100), ('110', 110), ('120', 120), ('130', 130), ('140', 140), ('150', 150), ('160', 160), ('170', 170), ('180', 180), ('190', 190), ('200', 200), ('210', 210), ('220', 220), ('230', 230), ('240', 240), ('250', 250), ('260', 260), ('270', 270), ('280', 280), ('290', 290), ('300', 300)], default='1'),
        ),
    ]
